PhoBo/Models/Booking.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PhoBo.Models
{
    public class Booking
    {
        [Key]
        public int Id { get; set; }
        [ForeignKey("Customer")]
        public int CustomerId { get; set; }
        public Customer Customer { get; set; }
        [ForeignKey("Photographer")]
        public int PhotographerId { get; set; }
        public Photographer Photographer { get; set; }
        [ForeignKey("Concept")]
        public int ConceptId { get; set; }
        public Concept Concept { get; set; }
        public DateTime BookingDate { get; set; }
        public float BookingRate { get; set; }
        [Required(ErrorMessage = "Duration is required")]
        public float Duration { get; set; }
        [Required(ErrorMessage = "Location is required")]
        public string Location { get; set; }
        public string Note { get; set; }
        [DefaultValue(BookingState.Waiting)]
        public BookingState State { get; set; }
    }
}

PhoBo/Pages/Bookings/Book.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PhoBo.Data;
using PhoBo.Models;

namespace PhoBo.Pages.Bookings
{
    public class BookModel : PageModel
    {
        private readonly PhoBo.Data.PhoBoContext _context;

        public BookModel(PhoBo.Data.PhoBoContext context)
        {
            _context = context;
        }

        public Customer Customer { get; set; }
        public Photographer Photographer { get; set; }
        public List<SelectListItem> PhotographerConcepts { get; set; }

        public IActionResult OnGet(int id)
        {
            Debug.WriteLine("GET");
            if (!_context.Photographer.Where(x => x.Id == id).Any())
            {
                return NotFound();
            }

            User currentUser = Auth.Auth.GetUser(HttpContext);
            Customer = _context.Customer.ToList().Find(c => c.Id == currentUser.Id);
            Photographer = _context.Photographer.Where(x => x.Id == id).FirstOrDefault();

            List<BookingConceptConfig> bookingConceptConfigs = _context.BookingConceptConfig.Include(bcc => bcc.Concept)
                .Where(bck => bck.PhotographerId == id)
                .ToList();

            if(bookingConceptConfigs.Count == 0) return NotFound();

            PhotographerConcepts = bookingConceptConfigs.Select(bcc =>
                new SelectListItem
                {
                    Value = bcc.ConceptId.ToString(),
                    Text = bcc.Concept.Name
                }
            ).ToList();
            return Page();
        }

        [BindProperty]
        public Booking Booking { get; set; }

        public async Task<IActionResult> OnPostAsync(int photographerId, int customerId)
        {
            //if (!ModelState.IsValid)
            //{
            //    return Page();
            //}
            Debug.WriteLine("POST");

            Booking.ConceptId = int.Parse(Request.Form["conceptId"]);
            Booking.CustomerId = customerId;
            Booking.PhotographerId = photographerId;
            Booking.Duration = float.Parse(Request.Form["duration"]);
            Booking.BookingDate = DateTime.Now;
            Booking.State = BookingState.Waiting;

            Debug.WriteLine($"DEBUG: {Booking.ConceptId} " +
                $"{Booking.CustomerId} " +
                $"{Booking.PhotographerId} " +
                $"{Booking.Duration} " +
                $"{Booking.Location} " +
                $"{Booking.Note} ");
            _context.Booking.Add(Booking);
            await _context.SaveChangesAsync();

            return Redirect("?id=" + photographerId);
        }

        public PartialViewResult OnGetDuration(int conceptId, int photographerId)
        {
            User currentUser = Auth.Auth.GetUser(HttpContext);
            string durationConfig = _context.BookingConceptConfig.ToList()
                .Find(bcc => bcc.ConceptId == conceptId && bcc.PhotographerId == photographerId)
                .DurationConfig;
            List<string> durationConfigList = durationConfig.Split(':').ToList();

            return Partial("_BookingDurationPartial", durationConfigList);
        }
    }
}

PhoBo/Pages/Bookings/Config.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PhoBo.Data;
using PhoBo.Models;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PhoBo.Pages.Bookings
{
    public class ConfigModel : PageModel
    {
        private readonly PhoBo.Data.PhoBoContext _context;

        public ConfigModel(PhoBoContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Photographer Photographer { get; set; }
        public User CurrentUser { get; set; }
        public List<BookingConceptConfig> BookingConceptConfigs { get; set; } 
        public IActionResult OnGet()
        {
            Debug.WriteLine($"[{this}]GET: ");

            CurrentUser = Auth.Auth.GetUser(HttpContext);

            if (CurrentUser == null || CurrentUser.Role != UserRole.Photographer)
            {
                return NotFound();
            }

            Photographer = _context.Photographer.Where(x => x.Id == CurrentUser.Id).FirstOrDefault();

            BookingConceptConfigs = _context.BookingConceptConfig.Include(bcc => bcc.Concept)
                .Where(bcc => bcc.PhotographerId == CurrentUser.Id)
                .ToList();

            return Page();
        }

        public JsonResult OnGetUpdateDurationConfig(int id, string duration)
        {
            try
            {
                List<BookingConceptConfig> bookingConceptConfigs = _context.BookingConceptConfig.Where(bcc => bcc.Id == id).ToList();
                if (bookingConceptConfigs.Any())
                {
                    bookingConceptConfigs[0].DurationConfig = duration;
                    _context.SaveChanges();
                }
                else
                {
                    return new JsonResult("id not found");
                }
            }
            catch (System.Exception ex)
            {
                return new JsonResult(ex.Message);
            }

            return new JsonResult("change successful");
        }

        public JsonResult OnGetDeleteDurationConfig(int id)
        {
            try
            {
                List<BookingConceptConfig> bookingConceptConfigs = _context.BookingConceptConfig.Where(bcc => bcc.Id == id).ToList();
                if (bookingConceptConfigs.Any())
                {
                    _context.Remove(bookingConceptConfigs[0]);
                    _context.SaveChanges();
                }
                else
                {
                    return new JsonResult("id not found");
                }
            }
            catch (System.Exception ex)
            {
                return new JsonResult(ex.Message);
            }

            return new JsonResult("delete successful");
        }

        public PartialViewResult OnGetAddConceptConfig(int photographerId)
        {
            System.Console.WriteLine("CONFIG");

            List<SelectListItem> conceptItems = _context.Concept.Where(c => !_context.BookingConceptConfig
                    .Where(bcc => bcc.PhotographerId == photographerId && bcc.ConceptId == c.Id)
                    .Any()
                 )
                .Select(c => new SelectListItem()
                {
                    Value = c.Id.ToString(),
                    Text = c.Name
                })
                .ToList();

            return Partial("_AddConceptConfigPartial", conceptItems);
        }

        public JsonResult OnPost(int id)
        {
            System.Console.WriteLine("photographerId " + id);
            BookingConceptConfig bookingConceptConfig = new BookingConceptConfig
            {
                ConceptId = int.Parse(Request.Form["conceptId"]),
                PhotographerId = id,
                DurationConfig = Request.Form["duration"]
            };

            _context.BookingConceptConfig.Add(bookingConceptConfig);
            _context.SaveChanges();

            return new JsonResult("add successful");
        }
    }
}

PhoBo/Pages/Bookings/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PhoBo.Data;
using PhoBo.Models;

namespace PhoBo.Pages.Bookings
{
    public class DeleteModel : PageModel
    {
        private readonly PhoBo.Data.PhoBoContext _context;

        public DeleteModel(PhoBo.Data.PhoBoContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Booking Booking { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Booking = await _context.Booking
                .Include(b => b.Concept)
                .Include(b => b.Customer)
                .Include(b => b.Photographer).FirstOrDefaultAsync(m => m.Id == id);

            if (Booking == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Booking = await _context.Booking.FindAsync(id);

            if (Booking != null)
            {
                _context.Booking.Remove(Booking);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

PhoBo/Pages/Bookings/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PhoBo.Data;
using PhoBo.Models;

namespace PhoBo.Pages.Bookings
{
    public class IndexModel : PageModel
    {
        private readonly PhoBo.Data.PhoBoContext _context;

        public IndexModel(PhoBo.Data.PhoBoContext context)
        {
            _context = context;
        }

        public User currentUser { get; set; }

        public IList<Booking> Booking { get;set; }

        public async Task<IActionResult> OnGetAsync()
        {
            Debug.WriteLine($"[{this}]GET: ");

            currentUser = Auth.Auth.GetUser(HttpContext);

            if (currentUser == null)
            {
                return NotFound();
            }

            Booking = await _context.Booking
                .Include(b => b.Concept)
                .Include(b => b.Customer)
                .Include(b => b.Photographer).ToListAsync();

            return Page();
        }

        public void OnPost()
        {
            Debug.WriteLine($"[{this}]POST:");
        }
        
        public JsonResult OnPostCancel(int id)
        {
            Debug.WriteLine($"[{this}]POST: id={id}");

            Booking booking = _context.Booking.ToList().Find(b => b.Id == id);

            if(!booking?.State.Equals(BookingState.Waiting) ?? false) return new JsonResult(new {result = "ERROR", value="Id not found"});

            booking.State = BookingState.Canceled;
            _context.SaveChanges();

            return new JsonResult(new { result = "OK", value = "Canceled"});
        }

        public JsonResult OnPostAccept(int id)
        {
            Debug.WriteLine($"[{this}]POST: id={id}");

            Booking booking = _context.Booking.ToList().Find(b => b.Id == id);

            if (!booking?.State.Equals(BookingState.Waiting) ?? false) return new JsonResult(new { result = "ERROR", value = "Id not found" });

            booking.State = BookingState.Accepted;
            _context.SaveChanges();

            return new JsonResult(new { result = "OK", value = "Accepted" });
        }

        public JsonResult OnPostDecline(int id)
        {
            Debug.WriteLine($"[{this}]POST: id={id}");

            Booking booking = _context.Booking.ToList().Find(b => b.Id == id);

            if (!booking?.State.Equals(BookingState.Waiting) ?? false) return new JsonResult(new { result = "ERROR", value = "Id not found" });

            booking.State = BookingState.Declined;
            _context.SaveChanges();

            return new JsonResult(new { result = "OK", value = "Declined" });
        }

        //public JsonResult OnPostRate(int id, float rate)
        //{
        //    Debug.WriteLine($"[{this}]POST: id={id}");

        //    Booking booking = _context.Booking.ToList().Find(b => b.Id == id);

        //    Console.WriteLine($"{(booking?.State.Equals(BookingState.Accepted) ?? false)} {!(booking?.BookingRate.Equals(0) ?? false)}");

        //    if (!(booking?.State.Equals(BookingState.Accepted) ?? false) && !(booking?.BookingRate.Equals(0) ?? false))  return new JsonResult(new { result = "ERROR", value = "can not rate" });

        //    booking.BookingRate = rate;
        //    //_context.SaveChanges();

        //    return new JsonResult(new { result = "OK", value = rate });
        //}

        public IActionResult OnPostRate(int id, float rate)
        {
            Debug.WriteLine($"[{this}]POST: id={id}");

            Booking booking = _context.Booking.ToList().Find(b => b.Id == id);

            if ((booking?.State.Equals(BookingState.Accepted) ?? false) && (booking?.BookingRate.Equals(0) ?? false))
            {
                booking.BookingRate = rate;
                _context.SaveChanges();
            }

            return RedirectToPage("./Index");
        }
    }
}

PhoBo/Pages/Bookings/Book.cshtml
@page
@model PhoBo.Pages.Bookings.BookModel

@{
    ViewData["Title"] = "Book";
    var photographer = Model.Photographer;
    var keyValuePairs = new Dictionary<string, string>
    {
        { "customerId", @Model.Customer.Id.ToString() },
        { "photographerId", @Model.Photographer.Id.ToString() }
    };
}

<h1>Booking</h1>

<h4>@Model.Photographer.Name</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label for="concept" class="control-label">Concept</label>
                <select id="concept" name="conceptId" asp-items="Model.PhotographerConcepts" class="form-select"></select>
            </div>
            <div id="duration" class="form-group">
            </div>
            <div class="form-group">
                <label asp-for="Booking.Location" class="control-label"></label>
                <input asp-for="Booking.Location" class="form-control" />
                <span asp-validation-for="Booking.Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Booking.Note" class="control-label"></label>
                <input asp-for="Booking.Note" class="form-control" />
                <span asp-validation-for="Booking.Note" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-all-route-data="keyValuePairs" type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
        loadDuration();
        $(function () {
            $('#concept').on('change', function () {
                console.log('change');
                loadDuration();
            });
        });

        function loadDuration() {
            let conceptId = $('#concept').val();
            $('#duration').load('?handler=Duration&conceptId=' + conceptId + "&photographerId=" + @photographer.Id, function() {
                $('#duration input[type="radio"]:first').trigger('click');
            });
        }
    </script>
}

PhoBo/Pages/Bookings/Index.cshtml
@page
@using PhoBo.Models
@model PhoBo.Pages.Bookings.IndexModel
@{
    User user = Model.currentUser;  
}

<link rel="stylesheet" type="text/css" href="~/css/booking-rate.css"/>

<h1>Booking history</h1>

<table class="table">
    <thead>
        <tr>
            @if (@user.Role.Equals(UserRole.Photographer))
            {
                <th>
                    @Html.DisplayNameFor(model => model.Booking[0].Customer)
                </th>
            }
            else if (@user.Role.Equals(UserRole.Customer))
            {
                <th>
                    @Html.DisplayNameFor(model => model.Booking[0].Photographer)
                </th>
            }
            <th>
                @Html.DisplayNameFor(model => model.Booking[0].Concept)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Booking[0].BookingDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Booking[0].BookingRate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Booking[0].Duration)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Booking[0].Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Booking[0].Note)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Booking[0].State)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Booking)
        {
            if 
            (
                @user.Role.Equals(UserRole.Photographer) && item.PhotographerId == @user.Id
                || @user.Role.Equals(UserRole.Customer) && item.CustomerId == @user.Id
            )
            {
                <tr>
                    @if (@user.Role.Equals(UserRole.Photographer))
                    {
                        <td>
                            <a asp-page="../Users/Details" asp-route-id="@item.CustomerId">@item.Customer.Name</a>
                        </td>
                    }
                    else if (@user.Role.Equals(UserRole.Customer))
                    {
                        <td>
                            <a asp-page="../Users/Details" asp-route-id="@item.PhotographerId">@item.Photographer.Name</a>
                        </td>
                    }
                    <td>
                        @Html.DisplayFor(modelItem => item.Concept.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BookingDate)
                    </td>
                    <td>
            
                        @if(item.State.Equals(BookingState.Accepted))
                        {
                            @if (user.Role.Equals(UserRole.Customer))
                            {
                                <form method="post" asp-page-handler="rate" asp-route-id="@item.Id" id="rate-form-@item.Id">
                                    <div class="full-star">
                                        <div class="rating-group" @(item.BookingRate > 0 ? "disabled": "")>
                                            
                                            <input @(item.BookingRate == 0 ? "checked": "") class="rating__input rating__input--none" name="rate" id="rating-none-@item.Id" value="0" type="radio">
                                            <label aria-label="1 star" class="rating__label" for="rating-1-@item.Id"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                                            <input @(item.BookingRate == 1 ? "checked": "") @(item.BookingRate > 0 ? "disabled": "") class="rating__input" name="rate" id="rating-1-@item.Id" value="1" type="radio" data-id="@item.Id">
                                            <label aria-label="2 stars" class="rating__label" for="rating-2-@item.Id"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                                            <input @(item.BookingRate == 2 ? "checked": "") @(item.BookingRate > 0 ? "disabled": "") class="rating__input" name="rate" id="rating-2-@item.Id" value="2" type="radio" data-id="@item.Id">
                                            <label aria-label="3 stars" class="rating__label" for="rating-3-@item.Id"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                                            <input @(item.BookingRate == 3 ? "checked": "") @(item.BookingRate > 0 ? "disabled": "") class="rating__input" name="rate" id="rating-3-@item.Id" value="3" type="radio" data-id="@item.Id">
                                            <label aria-label="4 stars" class="rating__label" for="rating-4-@item.Id"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                                            <input @(item.BookingRate == 4 ? "checked": "") @(item.BookingRate > 0 ? "disabled": "") class="rating__input" name="rate" id="rating-4-@item.Id" value="4" type="radio" data-id="@item.Id">
                                            <label aria-label="5 stars" class="rating__label" for="rating-5-@item.Id"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                                            <input @(item.BookingRate == 5 ? "checked": "") @(item.BookingRate > 0 ? "disabled": "") class="rating__input" name="rate" id="rating-5-@item.Id" value="5" type="radio" data-id="@item.Id">
                                        </div>
                                    </div>

        @*                           <div class="full-star">
                                        <div class="rating-group">
                                            <input checked class="rating__input rating__input--none" asp-for="@item.BookingRate" value="0" type="radio">
                                            <label aria-label="1 star" class="rating__label" asp-for="@item.BookingRate"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                                            <input class="rating__input" asp-for="@item.BookingRate" value="1" type="radio">
                                            <label aria-label="2 stars" class="rating__label" asp-for="@item.BookingRate"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                                            <input class="rating__input" asp-for="@item.BookingRate" value="2" type="text">
                                            <label aria-label="3 stars" class="rating__label" asp-for="@item.BookingRate"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                                            <input class="rating__input" asp-for="@item.BookingRate" value="3" type="radio">
                                            <label aria-label="4 stars" class="rating__label" asp-for="@item.BookingRate"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                                            <input class="rating__input" asp-for="@item.BookingRate" value="4" type="radio">
                                            <label aria-label="5 stars" class="rating__label" asp-for="@item.BookingRate"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                                            <input class="rating__input" asp-for="@item.BookingRate" value="5" type="radio">
                                        </div>
                                    </div>*@
                                </form>
                            }
                            else if (user.Role.Equals(UserRole.Photographer))
                            {
                                <div class="full-star">
                                    <div class="rating-group" disabled>
                                        <input @(item.BookingRate == 0 ? "checked": "") class="rating__input rating__input--none" name="rating-@item.Id" id="rating-none-@item.Id" value="0" type="radio">
                                        <label aria-label="1 star" class="rating__label" for="rating-1-@item.Id"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                                        <input @(item.BookingRate == 1 ? "checked": "") disabled class="rating__input" name="rating-@item.Id" id="rating-1-@item.Id" value="1" type="radio" data-id="@item.Id">
                                        <label aria-label="2 stars" class="rating__label" for="rating-2-@item.Id"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                                        <input @(item.BookingRate == 2 ? "checked": "") disabled class="rating__input" name="rating-@item.Id" id="rating-2-@item.Id" value="2" type="radio" data-id="@item.Id">
                                        <label aria-label="3 stars" class="rating__label" for="rating-3-@item.Id"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                                        <input @(item.BookingRate == 3 ? "checked": "") disabled class="rating__input" name="rating-@item.Id" id="rating-3-@item.Id" value="3" type="radio" data-id="@item.Id">
                                        <label aria-label="4 stars" class="rating__label" for="rating-4-@item.Id"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                                        <input @(item.BookingRate == 4 ? "checked": "") disabled class="rating__input" name="rating-@item.Id" id="rating-4-@item.Id" value="4" type="radio" data-id="@item.Id">
                                        <label aria-label="5 stars" class="rating__label" for="rating-5-@item.Id"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                                        <input @(item.BookingRate == 5 ? "checked": "") disabled class="rating__input" name="rating-@item.Id" id="rating-5-@item.Id" value="5" type="radio" data-id="@item.Id">
                                    </div>
                                </div>
                            }

                }
                        @*@Html.DisplayFor(modelItem => item.BookingRate)*@
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Duration)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Location)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Note)
                    </td>
                    <td id="booking-@item.Id-state">
                        @Html.DisplayFor(modelItem => item.State)
                    </td>
                    <td>
                        @*<a asp-page="./Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-page="./Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-page="./Delete" asp-route-id="@item.Id">Delete</a>*@
                        @Html.AntiForgeryToken()
                        <div>
                            @if(item.State.Equals(BookingState.Waiting))
                            {
                                @if(user.Role.Equals(UserRole.Photographer))
                                {
                                    <button data-action="Accept" data-id="@item.Id" class="booking-button btn btn-primary">Accept</button>
                                    <button data-action="Decline" data-id="@item.Id" class="booking-button btn btn-danger">Decline</button>
                                }
                                else if(user.Role.Equals(UserRole.Customer))
                                {  
                                    <button data-action="Cancel" data-id="@item.Id" class="booking-button btn btn-danger">Cancel</button>
                                }
                            }
                            
                            @if (item.State.Equals(BookingState.Accepted) && user.Role.Equals(UserRole.Customer) && item.BookingRate == 0)
                            {
                                <button data-action="Rate" data-id="@item.Id" class="rate-button btn btn-warning">Rate</button>
                            }
                        </div>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $(".booking-button").click(function() {
            let _this = $(this);
            let id = _this.data("id");
            let action = _this.data("action");
            let token = $('input[name="__RequestVerificationToken"]').val();

            console.log(`?handler=${action}`);

            $.ajax({
                url: `?handler=${action}`,
                headers: {"RequestVerificationToken": token},
                type: "POST",
                data: { id: id },
                success: function(response) {
                    if (response.result == "OK") {
                        _this.parent().remove();
                        $(`#booking-${id}-state`).html(response.value);
                    } else {
                        console.log(response.value);
                    }
                }
            });
        });

        $(".rate-button").click(function() {
            _this = $(this);
            $("#rate-form-" + _this.data("id")).trigger("submit");
        })
    </script>
}

PhoBo/Pages/Bookings/_AddConceptConfigPartial.cshtml
@model List<SelectListItem>
<form id="add-config-form" class="form-inline mt-3" method="post">
	<label for="concept" class="control-label mr-2">Concept</label>
	<select asp-items="Model" class="form-select mr-2" name="conceptId"></select>
	<label for="duration" class="control-label mr-2">Duration</label>
	<input id="add-duration" type="text" name="duration" class="form-control mr-2"/>
	<span id="add-duration-error" class="text-danger field-validation-valid"></span>
</form>

PhoBo/Pages/Bookings/_BookingDurationPartial.cshtml
@model List<String>
<label for="duration" class="control-label">Duration</label>
<div>
	@foreach(var @duration in Model)
	{
		<div class="form-check form-check-inline">
			  <input class="form-check-input" type="radio" name="duration" value="@duration" id="duration@Model.IndexOf(@duration)">
			  <label class="form-check-label" for="duration(@Model.IndexOf(@duration))">
				@duration
			  </label>
		</div>
	}
</div>